### ISSUE TITLE
🐛 IntelliSense tooltip never displayed in out-of-screen-bounds scenario - does not reappear when moving window back and changing the formula

### ISSUE THREAD

**Issue by wh1t3cAt1k** [Excel-DNA/IntelliSense#105]
Setup: master ExcelDna.IntelliSense (as of 2021-03-09)

Our original issue was that customers were complaining that sometimes (especially during Zoom screen demonstrations!) IntelliSense tooltips would stop working - no tooltip was being displayed at all.

Manifests like that:

![image](https://user-images.githubusercontent.com/5159662/110442019-784d9980-80cb-11eb-9ea2-39a6d6ed09eb.png)

We were observing this issue sporadically but were never able to catch it.

I decided to give it a bit more attention now and I could reproduce a suspiciously similar problem when part of the formula was out of the screen bounds. After that - no arguments highlighting, no argument description, nothing!

Does not help if one moves the cell back into screen or changes the formula value. Only clearing the formula and re-typing it again helps.

See the below video for the demonstration - after moving the cell out of screen, I used my keyboard to start typing the formula. Note how the formula selection window **does** appear, but the tooltip never does.

https://user-images.githubusercontent.com/5159662/110441496-e47bcd80-80ca-11eb-9c44-0c58a26db527.mp4

What could be at play here?

**Comment by govert** [comment]
It looks like some of the position tracking is not recovering once you move the window back into the desktop.

Some place like this would be a starting point: https://github.com/Excel-DNA/IntelliSense/blob/3ebb7657407cf2b3b6eef5dd8eb563198984be36/Source/ExcelDna.IntelliSense/UIMonitor/FormulaEditWatcher.cs#L352

It tends to be impossible to debug this kind of thing, due to the focus interactions. But you can try to switch on Verbose logging, and then wade through the thick logs to get to the right place.

**Comment by wh1t3cAt1k** [comment]
Actually this exception seems to happen all the time with various class names.

![image](https://user-images.githubusercontent.com/5159662/110455470-84405800-80d9-11eb-81c7-b894f6a83911.png)

Not sure if it's related to the original issue of the tooltip not showing.

**Comment by wh1t3cAt1k** [comment]
@govert (the issue with the _buffer seems to stem from the fact that it is a static variable - could it be a concurrent access problem with GetClassName?)

**Comment by wh1t3cAt1k** [comment]
@govert the issue seems to reproduce with easier steps, too:

1. Enter the formula in cell A1 like =MYFORMULA( with an opening bracket to force the tooltip to open.
2. Move Excel window boldly to the left so that the tooltip is well behind the screen boundaries (but part of Excel window remains visible).
3. Move Excel window back - observe that the tooltip has disappeared.

In `MoveToolTip()` handler, `Visible == true` and `Invalidate()` is called, but I can confirm that no repaint operation happens.

**Comment by govert** [comment]
The GetClassName error looks bad to me.
I made some changes last year to get the main GetClassName call to run from the main thread.
But your exception might be due top the Debug call at WinEvents.cs L:231.
You might want to change this line, or change the conditional compilation symbol - it's probably a bad idea to call GetClassName from here but printing the hWnd should be OK.

Otherwise I'm not surprised at the window tracking being a bit buggy. You'll probably find there is some expectation of the Window event sequence that I had that is just not true in this case.
It would be great to improve it if you find a plan :-)

**Comment by govert** [comment]
There a calculation somewhere that resizes the tooltip window, so that it doesn't fall off the screen on the right hand side if the description is long. Maybe you should check this - it might be doing something silly if the tooltip gets moved off the left side.

Something like TooltipForm.cs L:457

**Comment by wh1t3cAt1k** [comment]
@govert it definitely stops repainting forever (_or rather, until the tooltip is destroyed and recreated, e.g. by removing and reentering the opening bracket `(`_) , just as soon as the `left + width` becomes negative in this scenario (my log added):

![image](https://user-images.githubusercontent.com/5159662/110464354-164d5e00-80e4-11eb-9a19-19fc91d82d89.png)

I noticed how Excel native tooltip behaves in this scenario: the minimum `left` position for it is always zero. 

![image](https://user-images.githubusercontent.com/5159662/110464591-5b719000-80e4-11eb-8628-a55367b7d2a4.png)

Maybe DNA tooltip should behave the same way?

**Comment by wh1t3cAt1k** [comment]
This seems to help 

**One:** in `ShowToolTip()`:

![image](https://user-images.githubusercontent.com/5159662/110465648-bf488880-80e5-11eb-85e9-645d80c38db8.png)

**Two:** in `UpdateLocation()` handler:

![image](https://user-images.githubusercontent.com/5159662/110465304-4ba67b80-80e5-11eb-9679-c83d9ffea86a.png)

Result:

![image](https://user-images.githubusercontent.com/5159662/110465283-447f6d80-80e5-11eb-9178-4b778e2abfaa.png)

It's probably consistent with how Excel behaves.

It still does not help when I start typing the formula in a cell that is out-of-screen-bounds, probably a question of setting initial `_currentLeft` value

**Comment by wh1t3cAt1k** [comment]
@govert If you agree with this fix I can create a pull request.

**Comment by govert** [comment]
@wh1t3cAt1k Thank you for tracking this down. 
I was fiddling with the project, so I put your changes in too. Feel free to reopen the issue or add a new one if there are more of these niggles.
