### ISSUE TITLE
Not available on NuGet

### ISSUE THREAD

**Issue by akothoor** [Excel-DNA/IntelliSense#14]
Hello, so this Intellisense feature is not yet in production I assume?
How would I start using this if I wanted to add it to my Add-In ?

Thanks.

**Comment by govert** [comment]
First step is to test it as a separate add-in (32-bit only for now).
For this you just load the ExcelDna.IntelliSense.xll add-in (you can install it in the add-ins dialog with Alt+t, i). It should automatically pick up your descriptions for Excel-DNA add-ins v 0.32 and later.

Once we're sure this works, I'll prepare the integrated mode, where you can add it as a referenced library to your own .xll add-in.

**Comment by akothoor** [comment]
Okay, I installed the intellisense add-in. It displays the function description but does not display the argument help. I have it the description on each ExcelArgument as well.

**Comment by govert** [comment]
Does it look right in the normal function wizard?

What Excel and Windows version are you running?

When you are entering your function and you're at "=MyFunc(" so the list is no longer displayed, does it show anything (another window with the function name, description and argument names) or does it show nothing here?

**Comment by akothoor** [comment]
The function wizard looks the same. I am running Excel 2010 and Windows 7 Pro.

I only see the pop-up for function description =MyFunc.
When I start typing the arguments, there is no intellisense. 

![image](https://cloud.githubusercontent.com/assets/14793205/14822523/01d516dc-0b9d-11e6-9adb-ce8d9427ff5b.png)

**Comment by govert** [comment]
OK - I think need to test on Excel 2010 then.
I'll also make a version that has better logging to try to track this down.

**Comment by Ron-Ldn** [comment]
Is it related to this issue? https://github.com/Excel-DNA/IntelliSense/issues/1
This one is not fixed yet, but I am not sure whether it can be.

**Comment by govert** [comment]
@Ron-Ldn Are you saying you also don't see the Arguments help on Excel 2010?
How is that related to the editing issue of #4 ?

**Comment by Ron-Ldn** [comment]
Sorry I didn't quite get what akothoor problem was. 
I do get the Excel Arguments help. My issue is just that the highlighted arguments in the ExcelDna IntelliSense is not the edited one.

**Comment by govert** [comment]
I believe this Excel 2010 issue is fixed now.

**Comment by govert** [comment]
The NuGet packages will be here: https://www.nuget.org/packages/exceldna.intellisense
Instructions for using the 'Integrated Mode' with the NuGet packages are in the [Usage Instructions](https://github.com/Excel-DNA/IntelliSense/wiki/Usage-Instructions).

**Comment by akothoor** [comment]
This is awesome! thanks Govert.
I tried to integrate in my existing add-in and it works! (I basically added the IntelliSenseServer.Register(); function call in my AutoOpen() method).
However, when I try to debug (setting Start external program -  C:\Program Files (x86)\Microsoft Office\Office14\EXCEL.EXE) it always throws throws this error and the app breaks : 

**LoaderLock occured:**
Managed Debugging Assistant 'LoaderLock' has detected a problem in 'C:\Program Files (x86)\Microsoft Office\Office14\EXCEL.EXE'.

Additional information: Attempting managed execution inside OS Loader lock. Do not attempt to run managed code inside a DllMain or image initialization function since doing so can cause the application to hang.


When I remove the call to IntelliSenseServer.Register() in AutoOpen(), I can debug successfully. Is there a way to debug with the Intellisense dll integrated into the current add-in ?


Thanks.

**Comment by govert** [comment]
You can safely ignore that warning, and you might like to tell Visual Studio not to show it again.

-Govert

On 18 Jul 2016, at 22:04, akothoor <notifications@github.com<mailto:notifications@github.com>> wrote:


This is awesome! thanks Govert.
I tried to integrate in my existing add-in and it works! (I basically added the IntelliSenseServer.Register(); function call in my AutoOpen() method).
However, when I try to debug (setting Start external program - C:\Program Files (x86)\Microsoft Office\Office14\EXCEL.EXE) it always throws throws this error and the app breaks :

LoaderLock occured:
Managed Debugging Assistant 'LoaderLock' has detected a problem in 'C:\Program Files (x86)\Microsoft Office\Office14\EXCEL.EXE'.

Additional information: Attempting managed execution inside OS Loader lock. Do not attempt to run managed code inside a DllMain or image initialization function since doing so can cause the application to hang.

When I remove the call to IntelliSenseServer.Register() in AutoOpen(), I can debug successfully. Is there a way to debug with the Intellisense dll integrated into the current add-in ?

Thanks.

**Comment by akothoor** [comment]
Oh I see okay. I read that it is because managed code may get executed during dllMain. Is there a way around this ? Would it cause any potential issues in the future ?
As long as this is production ready, then it should be fine. 

Thanks.

**Comment by govert** [comment]
Maybe it's a bit risky, but I understand the reason for the warning, and I've tried to be careful about the work we do in that DllMain context.
I don't know of a better way to track which modules are loaded in the process - otherwise we need to do some kind of polling all the time, which I think is worse.

I'd certainly like to know if you run into any instability.
