### ISSUE TITLE
Excel doesn't open on recent/new documents pane using IntelliSenseServer.Register

### ISSUE THREAD

**Issue by LBuckland** [Excel-DNA/IntelliSense#39]
I am trying to bring together two separate development efforts; one an ExcelDna XLL add-in, which includes the ExcelDna.IntelliSense DLL, and the other a VSTO add-in.  Individually they work well, and perform as expected.  The problem comes when I try to bring them together, using Application.RegisterXLL within the VSTO add-in to load the packed version of the XLL, Excel opens up at a blank screen (as you would get when you close the last remaining document without exiting), rather than the screen that displays the recent files and the new file templates.  From here, I can go to File and select New, so it's not a big deal, but it's just not what a user expects.  If I comment out the IntelliSenseServer.Register() command, then Excel performs as expected, but doesn't have IntelliSense for the XLL add-in functions.

Any thoughts/help would be appreciated.

**Comment by govert** [comment]
What happens if you load the IntelliSense as an independent add-in - i.e. Load the ExcelDna.InltelliSense.xll using RegisterXLL after loading your add-in?



On 15 Nov 2016, at 01:29, LBuckland <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to bring together two separate development efforts; one an ExcelDna XLL add-in, which includes the ExcelDna.IntelliSense DLL, and the other a VSTO add-in. Individually they work well, and perform as expected. The problem comes when I try to bring them together, using Application.RegisterXLL within the VSTO add-in to load the packed version of the XLL, Excel opens up at a blank screen (as you would get when you close the last remaining document without exiting), rather than the screen that displays the recent files and the new file templates. From here, I can go to File and select New, so it's not a big deal, but it's just not what a user expects. If I comment out the IntelliSenseServer.Register() command, then Excel performs as expected, but doesn't have IntelliSense for the XLL add-in functions.

Any thoughts/help would be appreciated.

**Comment by LBuckland** [comment]
Loading the XLL via RegisterXLL gives me the same result, regardless of whether I load my ExcelDna add-in or not.

**Comment by govert** [comment]
@LBuckland Could you confirm your exact Excel version?

I'm seeing similar behaviour with any .xll installed (Excel-DNA add-ins or native .xll add-ins), and believe this might be an Excel bug. See this discussion: https://groups.google.com/forum/#!topic/exceldna/eJtRC-MnkrI

You report this only happening when the IntelliSense library is loaded, though...

**Comment by LBuckland** [comment]
Excel 2016 MSO (16.0.4498.1000) 32-bit

For now I'm running the two components individually.

**Comment by hell-racer** [comment]
According to that same link (https://groups.google.com/forum/#!topic/exceldna/eJtRC-MnkrI) the Excel bug is fixed now. I never did see it appearing on Office 365 (16.0.8730.2175 Click-to-Run) 64 bit and Pro Plus 2016 (16.0.4639.1000) 64 bit.
