### ISSUE TITLE
WorkbookActivate not fired when IntelliSense registered

### ISSUE THREAD

**Issue by klimovgv** [Excel-DNA/IntelliSense#47]
Got a sample project [here](https://drive.google.com/open?id=0B3dAUkg3XOnLLW1xWXBVQWFMVlk) to demonstrate behavior.

The idea is to substitute a function inserted on a sheet with a plain text.
There is =TestFunction1(), when inserted should be replaced with text "TestFunction1Replaced".

If IntelliSenseServer.Register() line is commented - everything is working,
if it's there - then the function is not replaced with text.

I've got Windows 8.1 Enterprise x64, Office 2016 Professional Plus x86 (16.0.8067.2115)

PS Thank you for excellent ExcelDNA project!

**Comment by govert** [comment]
I got the sample project and see the unexpected behaviour.

**Comment by govert** [comment]
@klimovgv I think you're getting tricked up by the garbage collector, and that the IntelliSense support is just causing the GC to run more often. To see this:

1. Comment out the 1IntelliSenseServer.Register()` line or remove the IntelliSense reference completely.

2. Add an extra function that will run the GC on demand:
```c#
        [ExcelFunction]
        public static string RunGC()
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
            return "GC was run";
        }
```
3. Run in Excel. Enter `=TestFunction`()` and see that your substitution happens. Now call `=RunGC()`. Then enter `=TestFunction1()` again - the substitution no longer happens.

To fix your code so that it works right, you need to keep a reference to the active workbook in your code. This will ensure that the .NET GC does not collect it, causing your event handlers to get detached.

**Comment by klimovgv** [comment]
@govert Thank you, that was the case indeed!
Keeping the reference now and everything is fine.
