### ISSUE TITLE
Exception when function has no Description attribute 

### ISSUE THREAD

**Issue by garethhayter** [Excel-DNA/IntelliSense#5]
When a function is decorated with the [ExcelFunction] attribute, and the Name argument is not specified but Description is specified, then when the function is highlighted on the IntelliSense list, a NullReferenceException is thrown in ExcelDna.IntelliSense.IntelliSenseDisplay.GetFunctionDescription() when it tries to access the null Description property.

Also, when the Name argument is omitted but Description is included, then the function doesn't even show in the IntelliSense list. Shouldn't it default to the function's name in the code, via Reflection?

**Comment by Ron-Ldn** [comment]
Hi Gareth,
What version of the code did you test ? There was a conflict with the xll versions since my last commit. I need to upload the latest ExcelDna.IntelliSense.xll, but I can't right now (will do tomorrow).
If you check out the latest version of the code, manually copy ExcelDna.xll to ExcelDna.IntelliSense.xll, and then build, it should be better.
Do you still observe the issue ? I can't reproduce on my side.

**Comment by govert** [comment]
This one should be fine now.
