### ISSUE TITLE
IntelliSense on 64-bit crashes Explorer.exe when Win+D is pressed

### ISSUE THREAD

**Issue by govert** [Excel-DNA/IntelliSense#65]
From this discusison: https://groups.google.com/forum/#!topic/exceldna/y1GB0WM_Hh4

**Comment by nVenticDW** [comment]
I seem to get the same crashing on the same configuration. I hardly ever use Win+D so I've never seen it before
I only see it by a spinner circle while it restarts the file explorer and 1/5th second screen blackness
W10x64 1804,
Excel 2016 x64
intellisense called by having an _InteliSense_ workbook in an addin though File explorer also restarts when no addin using intellisense is auto-loaded or loaded.

**Comment by WizardsEnterprise** [comment]
Here is my project that is doing it on any computer that I install the addin on. It has nothing but a simple UDF that accepts a cell reference that contains a date, it takes the date and codifies it in YYYYMM and returns as a string. https://www.dropbox.com/s/g01wzsvyldt4i2n/ExcelUDFTest.zip?dl=0

Project was created in VS2017 Community
All test computers have the following specs:

- Windows 10 x64
- Excel 2016 x64
- Using the x64 packed version of the add-in because Intellisense is packed for easy distribution of a single file with no installer needed.

**Comment by WizardsEnterprise** [comment]
@nVenticDW can you make an AutoHotKey macro to intercept the WinKey D shortcut and instead execute Shell32.Shell.ToggleDesktop()

Can be done using whatever platform you're most familiar with but AutoHotKey is really simple because it does the work of hooking up the keyboard for you. In theory, when windows natively handles that shortcut it is just supposed to be calling this same code, but if I intercept the shortcut and execute that code myself it shows the desktop without crashing explorer.exe.

**Comment by govert** [comment]
I can reproduce on 64-bit Excel.

**Comment by govert** [comment]
The problem is definitely not related to the LoaderLock callback.

The problem is related to the WinEvents callback the the IntelliSense uses to track the window locations. During the WIN+D handling, Explorer.exe generates some WinEvents that are delivered according to the callback set up by the IntelliSense.

For some reason that I do not understand yet, Explorer.exe is trying to load the IntelliSense.xll into it's own process, and from there the crash follows. I found some old messages reporting the same problem, with the unhelpful answer that a native .dll does not have this problem. I think Explorer.exe is loading the module because the WinEvent is being registered with the WINEVENT_INCONTEXT flag. Maybe this is not right, since in this case the Explorer.exe is generating the relevant WinEvents and we definitely don't want to be in that context.

I suspect the reason why there is no similar problem with 32-bit Excel on 64-bit Windows is that the 64-bit Explorer.exe could not load the 32-bit .xll module. I want to test with 32-bit Windows and 32-bit Excel, and kind of expect Explorer.exe to crash in that context too.

**Comment by govert** [comment]
This should be fixed with commit 3922e0f45c0251e3f77cd4fc30eefd1e36914248, released in version 1.0.9
